### ISSUE TITLE
Inconsistent use of language - `result` vs `output`

### ISSUE THREAD

**Issue by probinso** [GaloisInc/ppaml-eval-tools#13]
eval should take in `output` and write to `result` not the other way around

**Comment by mhuesch** [comment]
My interpretation is that `eval.sh` takes in `result` (the result of `run.sh`) and then writes the evaluation output to `output`. So the current language seems reasonable to me. I'm going to close this since changing it will confuse me, and probably not benefit any future readers of the code (I may be wrong though!).
